/* empty css                      */import{S as u,N as p,P as f}from"./assets/vendor-25e36fe5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const e of n)if(e.type==="childList")for(const s of e.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function i(n){const e={};return n.integrity&&(e.integrity=n.integrity),n.referrerPolicy&&(e.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?e.credentials="include":n.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function r(n){if(n.ep)return;n.ep=!0;const e=i(n);fetch(n.href,e)}})();(()=>{const t=document.querySelector(".js-menu-container"),o=document.querySelector(".js-open-menu"),i=document.querySelector(".js-close-menu"),r=()=>{const e=t.querySelectorAll('a[href*="#"]'),s=o.getAttribute("aria-expanded")==="true"||!1;o.setAttribute("aria-expanded",!s),t.classList.toggle("is-open");const d=s?"enableBodyScroll":"disableBodyScroll";if(bodyScrollLock[d](document.body),e.length!==0){if(!s){e.forEach(a=>{a.addEventListener("click",r)});return}e.forEach(a=>{a.removeEventListener("click",r)})}},n=e=>{e.target===e.currentTarget&&r()};t.addEventListener("click",n),o.addEventListener("click",r),i.addEventListener("click",r),window.matchMedia("(min-width: 1199.98px)").addEventListener("change",e=>{e.matches&&(t.classList.remove("is-open"),o.setAttribute("aria-expanded",!1),bodyScrollLock.enableBodyScroll(document.body))})})();new u(".swiper",{modules:[p,f],direction:"horizontal",loop:!0,pagination:{el:".swiper-pagination"},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}});const h=[{question:"How do I start playing Bubble Candy?",answer:"Download from the Play Store and press 'Play'."},{question:"Is this game free?",answer:"Yes, but it offers optional in-app purchases."},{question:"Can I play without an internet connection?",answer:"Yes, Bubble Candy supports offline play."},{question:"How often are new levels added?",answer:"New levels are regularly added with updates."},{question:"Are there any special events?",answer:"Yes, seasonal events and challenges are held for additional rewards."}],m=document.querySelector(".accordion-thumb");function g(){const t=h.map(o=>`<li class="accordion-wrapper">
        <button class="accordion" type="button">
          <p>${o.question}</p>
          <svg width="24" height="24">
            <use
              class="accordion-chevron-down"
              href="/assets/sprite.svg#icon-ChevronDown"
            ></use>
          </svg>
        </button>
        <div class="panel">
          <p>${o.answer}</p>
        </div>
      </li>`).join("");m.innerHTML=t}g();const l=document.querySelectorAll(".accordion");c(l[0]);l.forEach(t=>{t.addEventListener("click",y)});function y(){const t=document.querySelector(".accordion[data-expanded]");t&&t!==this&&c(t),c(this)}function c(t){t.classList.toggle("active"),t.dataset.expanded===void 0?t.dataset.expanded="":delete t.dataset.expanded;const o=t.nextElementSibling;o.style.maxHeight?o.style.maxHeight=null:o.style.maxHeight=o.scrollHeight+"px"}
//# sourceMappingURL=commonHelpers.js.map
